### PR TITLE
Tornado tasker

### PR DESCRIPTION
**Pull request by z0r0z**
tornado (nova) tasker

### CODE REVIEW

**Comment by sarangparikh22** [comment]
@z0r0z Do you think we should also give support to swap to WETH? since most streams wouldn't be in WETH.

**Comment by z0r0z** [comment]
@sarangparikh22 I am thinking the simplest solution to integrate swap is to incorporate the Swap Taskers into Tornado Tasker. So, user would send payload for `batch()` with different calls to loop for `onTaskReceived()` to accomplish swap and tornado wrap. This combined contract therefore looks more like a generalized tasker.

**Comment by sarangparikh22** [comment]
@z0r0z yes that makes sense, but we have to do some more additions, like check that only supported asset can be used, but yeah, I agree, you can just merge the Swap Tasker with this. I still prefer keeping it separate. Wdyt?

**Comment by z0r0z** [comment]
well, yk

**Pull request closed without merging**
